name: tailscale ssh
on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: dump info
        run: |
          id
          pwd

      - uses: tailscale/github-action@main
        with:
          oauth-client-id: ${{ vars.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          args: --ssh
          hostname: actions

      - run: sleep infinity

      - run: sudo tailscale logout
        if: ${{ always() }}
