name: tailscale ssh
on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: dump info
        run: |
          id
          pwd

      - uses: tailscale/github-action@main
        with:
          oauth-client-id: ${{ vars.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:github-actions
          args: --ssh
          hostname: actions
          version: 1.60.1

      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "<@316911818725392384>"
          description: |
            **GitHub Actions SSH is ready!**

            Run `ssh -o StrictHostKeyChecking=no runner@actions` to connect.

      - run: sleep infinity

      - run: sudo tailscale logout
        if: ${{ always() }}
        id: logout

      - uses: sarisia/actions-status-discord@v1
        if: ${{ always() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ steps.logout.outcome }}
          content: "<@316911818725392384>"
          title: GitHub Actions SSH Shutdown status
